# -*- coding: utf-8 -*-
"""python_calculator_app_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tXm2yXn_aTeDikHiuWalk_Zan992BoZE

**1: Simple Calculator for simple way to udestand**
"""

user_1 = int(input("Enter first number: "))
user_2 = int(input("Enter second number: "))

print("Addtion with Numbers: ",user_1 + user_2)
print("Subtraction with Numbers: ",user_1 - user_2)
print("Multiply with Numbers: ",user_1 * user_2)
print("Divsion with Numbers: ",user_1 / user_2)

"""**2:  We have created  Calculator and logic building**"""

def calculator(num_1, num_2, opperator):
  if opperator == "+": ## If Opperator equal to "+" Symbol then Add both number, which giving to parameter num_1 & num_2 during function calling Arguments.
    sum = num_1+num_2
    return sum

  if opperator == "-": ## If Opperator equal to "+" Symbol then Subtraction both number, which giving to parameter num_1 & num_2 during function calling Arguments.
    subt = num_1-num_2
    return subt

  if opperator == "*": ## If Opperator equal to "+" Symbol then multiply both number, which giving to parameter num_1 & num_2 during function calling Arguments.
    mul = num_1*num_2
    return mul

  if opperator == "/": ## If Opperator equal to "/" Symbol then divided both number, which giving to parameter num_1 & num_2 during function calling Arguments.
    div = num_1/num_2
    return div

print(calculator(4,7, "+"))
print(calculator(20,7, "-"))
print(calculator(4,12, "*"))
print(calculator(120,15, "/"))

"""**3: Now  We  created  (Calculator Type Style) and logic building**"""

def calculator(user1,user2, opperator):
  if opperator == "+": ## If Opperator equal to "+" Symbol then Add both number, which giving to parameter num_1 & num_2 during function calling Arguments.
    sum = user1 + user2
    return sum

  if opperator == "-": ## If Opperator equal to "+" Symbol then Subtraction both number, which giving to parameter num_1 & num_2 during function calling Arguments.
    sub = user1 - user2
    return sub

  if opperator == "*": ## If Opperator equal to "+" Symbol then multiply both number, which giving to parameter num_1 & num_2 during function calling Arguments.
    mul = user1 * user2
    return mul

  if opperator == "/": ## If Opperator equal to "/" Symbol then divided both number, which giving to parameter num_1 & num_2 during function calling Arguments.
    div = user1 / user2
    return div

user1 = float(input("Enter the first Number: "))
user2 = input("Enter the Operator: or Symbol like +  -  *  / ")
user3 = float(input("Enter the second Number: "))
calculator(user1, user3,user2 )

